/*
 * Decompiled with CFR 0.152.
 */
public class afi {
    public static final afh a;
    public static final afh b;
    public static final ahe c;
    public static final afh d;
    public static final afh e;
    public static final afh f;
    public static final afh g;
    public static final afh h;
    public static final agl i;
    public static final ajw j;
    public static final agl k;
    public static final ajw l;
    public static final ajh m;
    public static final afh n;
    public static final afh o;
    public static final afh p;
    public static final afh q;
    public static final afh r;
    public static final afh s;
    public static final ahs t;
    public static final ahs u;
    public static final afh v;
    public static final afh w;
    public static final afh x;
    public static final afh y;
    public static final afh z;
    public static final afh A;
    public static final afh B;
    public static final afh C;
    public static final afh D;
    public static final afh E;
    public static final als F;
    public static final afh G;
    public static final akc H;
    public static final agb I;
    public static final als J;
    public static final alt K;
    public static final afh L;
    public static final alv M;
    public static final agw N;
    public static final agw O;
    public static final afm P;
    public static final afm Q;
    public static final afh R;
    public static final afh S;
    public static final ahh T;
    public static final ahh U;
    public static final afh V;
    public static final afh W;
    public static final afh X;
    public static final afh Y;
    public static final afh Z;
    public static final afh aa;
    public static final agv ab;
    public static final afh ac;
    public static final afh ad;
    public static final afs ae;
    public static final ajb af;
    public static final afh ag;
    public static final afh ah;
    public static final afh ai;
    public static final afh aj;
    public static final afh ak;
    public static final afh al;
    public static final afh am;
    public static final afh an;
    public static final afh ao;
    public static final afh ap;
    public static final afh aq;
    public static final afh ar;
    public static final afh as;
    public static final afh at;
    public static final afh au;
    public static final afh av;
    public static final afh aw;
    public static final afh ax;
    public static final afh ay;
    public static final afh az;
    public static final afh aA;
    public static final afh aB;
    public static final afh aC;
    public static final afh aD;
    public static final afh aE;
    public static final afh aF;
    public static final afh aG;
    public static final afh aH;
    public static final afh aI;
    public static final afh aJ;
    public static final afo aK;
    public static final afh aL;
    public static final aje aM;
    public static final afh aN;
    public static final afh aO;
    public static final afh aP;
    public static final afh aQ;
    public static final afh aR;
    public static final afh aS;
    public static final afh aT;
    public static final afh aU;
    public static final afh aV;
    public static final afh aW;
    public static final afh aX;
    public static final aip aY;
    public static final afh aZ;
    public static final afh ba;
    public static final ajf bb;
    public static final ajf bc;
    public static final afh bd;
    public static final afh be;
    public static final afh bf;
    public static final afh bg;
    public static final afh bh;
    public static final afh bi;
    public static final afh bj;
    public static final afh bk;
    public static final afh bl;
    public static final afh bm;
    public static final afh bn;
    public static final afh bo;
    public static final afh bp;
    public static final afh bq;
    public static final afh br;
    public static final afh bs;
    public static final afh bt;
    public static final afh bu;
    public static final afh bv;
    public static final aib bw;
    public static final afh bx;
    public static final afh by;
    public static final afh bz;
    public static final afh bA;
    public static final afh bB;
    public static final afh bC;
    public static final afh bD;
    public static final afr bE;
    public static final afh bF;
    public static final afh bG;
    public static final afh bH;
    public static final afh bI;
    public static final afh bJ;
    public static final afh bK;
    public static final ahh bL;
    public static final ahh bM;
    public static final afh bN;
    public static final afh bO;
    public static final afh bP;
    public static final afh bQ;
    public static final akj bR;
    public static final afh bS;
    public static final afh bT;
    public static final afh bU;
    public static final afh bV;
    public static final afh bW;
    public static final afh bX;
    public static final aff bY;
    public static final afh bZ;
    public static final afh ca;
    public static final afh cb;
    public static final afh cc;
    public static final afh cd;
    public static final ajm ce;
    public static final afh cf;
    public static final afh cg;
    public static final afh ch;
    public static final afh ci;
    public static final afx cj;
    public static final afx ck;
    public static final aga cl;
    public static final aga cm;
    public static final afh cn;
    public static final afh co;
    public static final ahn cp;
    public static final afh cq;
    public static final afh cr;
    public static final afh cs;
    public static final afh ct;
    public static final afh cu;
    public static final afh cv;
    public static final afh cw;
    public static final afh cx;
    public static final afh cy;
    public static final afh cz;
    public static final afh cA;
    public static final afh cB;
    public static final afh cC;
    public static final afh cD;
    public static final afh cE;
    public static final agi cF;
    public static final ajs cG;
    public static final ajt cH;
    public static final afh cI;
    public static final afh cJ;
    public static final afh cK;
    public static final afh cL;
    public static final afh cM;
    public static final afh cN;
    public static final ahh cO;
    public static final ahh cP;

    private static afh a(String string) {
        return afh.c.a(new jy(string));
    }

    static {
        if (!kb.a()) {
            throw new RuntimeException("Accessed Blocks before Bootstrap!");
        }
        a = afi.a("air");
        b = afi.a("stone");
        c = (ahe)afi.a("grass");
        d = afi.a("dirt");
        e = afi.a("cobblestone");
        f = afi.a("planks");
        g = afi.a("sapling");
        h = afi.a("bedrock");
        i = (agl)afi.a("flowing_water");
        j = (ajw)afi.a("water");
        k = (agl)afi.a("flowing_lava");
        l = (ajw)afi.a("lava");
        m = (ajh)afi.a("sand");
        n = afi.a("gravel");
        o = afi.a("gold_ore");
        p = afi.a("iron_ore");
        q = afi.a("coal_ore");
        r = afi.a("log");
        s = afi.a("log2");
        t = (ahs)afi.a("leaves");
        u = (ahs)afi.a("leaves2");
        v = afi.a("sponge");
        w = afi.a("glass");
        x = afi.a("lapis_ore");
        y = afi.a("lapis_block");
        z = afi.a("dispenser");
        A = afi.a("sandstone");
        B = afi.a("noteblock");
        C = afi.a("bed");
        D = afi.a("golden_rail");
        E = afi.a("detector_rail");
        F = (als)afi.a("sticky_piston");
        G = afi.a("web");
        H = (akc)afi.a("tallgrass");
        I = (agb)afi.a("deadbush");
        J = (als)afi.a("piston");
        K = (alt)afi.a("piston_head");
        L = afi.a("wool");
        M = (alv)afi.a("piston_extension");
        N = (agw)afi.a("yellow_flower");
        O = (agw)afi.a("red_flower");
        P = (afm)afi.a("brown_mushroom");
        Q = (afm)afi.a("red_mushroom");
        R = afi.a("gold_block");
        S = afi.a("iron_block");
        T = (ahh)afi.a("double_stone_slab");
        U = (ahh)afi.a("stone_slab");
        V = afi.a("brick_block");
        W = afi.a("tnt");
        X = afi.a("bookshelf");
        Y = afi.a("mossy_cobblestone");
        Z = afi.a("obsidian");
        aa = afi.a("torch");
        ab = (agv)afi.a("fire");
        ac = afi.a("mob_spawner");
        ad = afi.a("oak_stairs");
        ae = (afs)afi.a("chest");
        af = (ajb)afi.a("redstone_wire");
        ag = afi.a("diamond_ore");
        ah = afi.a("diamond_block");
        ai = afi.a("crafting_table");
        aj = afi.a("wheat");
        ak = afi.a("farmland");
        al = afi.a("furnace");
        am = afi.a("lit_furnace");
        an = afi.a("standing_sign");
        ao = afi.a("wooden_door");
        ap = afi.a("spruce_door");
        aq = afi.a("birch_door");
        ar = afi.a("jungle_door");
        as = afi.a("acacia_door");
        at = afi.a("dark_oak_door");
        au = afi.a("ladder");
        av = afi.a("rail");
        aw = afi.a("stone_stairs");
        ax = afi.a("wall_sign");
        ay = afi.a("lever");
        az = afi.a("stone_pressure_plate");
        aA = afi.a("iron_door");
        aB = afi.a("wooden_pressure_plate");
        aC = afi.a("redstone_ore");
        aD = afi.a("lit_redstone_ore");
        aE = afi.a("unlit_redstone_torch");
        aF = afi.a("redstone_torch");
        aG = afi.a("stone_button");
        aH = afi.a("snow_layer");
        aI = afi.a("ice");
        aJ = afi.a("snow");
        aK = (afo)afi.a("cactus");
        aL = afi.a("clay");
        aM = (aje)afi.a("reeds");
        aN = afi.a("jukebox");
        aO = afi.a("fence");
        aP = afi.a("spruce_fence");
        aQ = afi.a("birch_fence");
        aR = afi.a("jungle_fence");
        aS = afi.a("dark_oak_fence");
        aT = afi.a("acacia_fence");
        aU = afi.a("pumpkin");
        aV = afi.a("netherrack");
        aW = afi.a("soul_sand");
        aX = afi.a("glowstone");
        aY = (aip)afi.a("portal");
        aZ = afi.a("lit_pumpkin");
        ba = afi.a("cake");
        bb = (ajf)afi.a("unpowered_repeater");
        bc = (ajf)afi.a("powered_repeater");
        bd = afi.a("trapdoor");
        be = afi.a("monster_egg");
        bf = afi.a("stonebrick");
        bg = afi.a("brown_mushroom_block");
        bh = afi.a("red_mushroom_block");
        bi = afi.a("iron_bars");
        bj = afi.a("glass_pane");
        bk = afi.a("melon_block");
        bl = afi.a("pumpkin_stem");
        bm = afi.a("melon_stem");
        bn = afi.a("vine");
        bo = afi.a("fence_gate");
        bp = afi.a("spruce_fence_gate");
        bq = afi.a("birch_fence_gate");
        br = afi.a("jungle_fence_gate");
        bs = afi.a("dark_oak_fence_gate");
        bt = afi.a("acacia_fence_gate");
        bu = afi.a("brick_stairs");
        bv = afi.a("stone_brick_stairs");
        bw = (aib)afi.a("mycelium");
        bx = afi.a("waterlily");
        by = afi.a("nether_brick");
        bz = afi.a("nether_brick_fence");
        bA = afi.a("nether_brick_stairs");
        bB = afi.a("nether_wart");
        bC = afi.a("enchanting_table");
        bD = afi.a("brewing_stand");
        bE = (afr)afi.a("cauldron");
        bF = afi.a("end_portal");
        bG = afi.a("end_portal_frame");
        bH = afi.a("end_stone");
        bI = afi.a("dragon_egg");
        bJ = afi.a("redstone_lamp");
        bK = afi.a("lit_redstone_lamp");
        bL = (ahh)afi.a("double_wooden_slab");
        bM = (ahh)afi.a("wooden_slab");
        bN = afi.a("cocoa");
        bO = afi.a("sandstone_stairs");
        bP = afi.a("emerald_ore");
        bQ = afi.a("ender_chest");
        bR = (akj)afi.a("tripwire_hook");
        bS = afi.a("tripwire");
        bT = afi.a("emerald_block");
        bU = afi.a("spruce_stairs");
        bV = afi.a("birch_stairs");
        bW = afi.a("jungle_stairs");
        bX = afi.a("command_block");
        bY = (aff)afi.a("beacon");
        bZ = afi.a("cobblestone_wall");
        ca = afi.a("flower_pot");
        cb = afi.a("carrots");
        cc = afi.a("potatoes");
        cd = afi.a("wooden_button");
        ce = (ajm)afi.a("skull");
        cf = afi.a("anvil");
        cg = afi.a("trapped_chest");
        ch = afi.a("light_weighted_pressure_plate");
        ci = afi.a("heavy_weighted_pressure_plate");
        cj = (afx)afi.a("unpowered_comparator");
        ck = (afx)afi.a("powered_comparator");
        cl = (aga)afi.a("daylight_detector");
        cm = (aga)afi.a("daylight_detector_inverted");
        cn = afi.a("redstone_block");
        co = afi.a("quartz_ore");
        cp = (ahn)afi.a("hopper");
        cq = afi.a("quartz_block");
        cr = afi.a("quartz_stairs");
        cs = afi.a("activator_rail");
        ct = afi.a("dropper");
        cu = afi.a("stained_hardened_clay");
        cv = afi.a("barrier");
        cw = afi.a("iron_trapdoor");
        cx = afi.a("hay_block");
        cy = afi.a("carpet");
        cz = afi.a("hardened_clay");
        cA = afi.a("coal_block");
        cB = afi.a("packed_ice");
        cC = afi.a("acacia_stairs");
        cD = afi.a("dark_oak_stairs");
        cE = afi.a("slime");
        cF = (agi)afi.a("double_plant");
        cG = (ajs)afi.a("stained_glass");
        cH = (ajt)afi.a("stained_glass_pane");
        cI = afi.a("prismarine");
        cJ = afi.a("sea_lantern");
        cK = afi.a("standing_banner");
        cL = afi.a("wall_banner");
        cM = afi.a("red_sandstone");
        cN = afi.a("red_sandstone_stairs");
        cO = (ahh)afi.a("double_stone_slab2");
        cP = (ahh)afi.a("stone_slab2");
    }
}

