/*
 * Decompiled with CFR 0.152.
 */
public class zy {
    public static final zw a;
    public static final zw b;
    public static final zw c;
    public static final zw d;
    public static final zw e;
    public static final yt f;
    public static final zw g;
    public static final zw h;
    public static final zw i;
    public static final zw j;
    public static final zw k;
    public static final zw l;
    public static final zw m;
    public static final zw n;
    public static final zw o;
    public static final zw p;
    public static final zw q;
    public static final zw r;
    public static final zw s;
    public static final zw t;
    public static final zw u;
    public static final zw v;
    public static final zw w;
    public static final zw x;
    public static final zw y;
    public static final zw z;
    public static final zw A;
    public static final zw B;
    public static final zw C;
    public static final zw D;
    public static final zw E;
    public static final zw F;
    public static final zw G;
    public static final zw H;
    public static final zw I;
    public static final zw J;
    public static final zw K;
    public static final zw L;
    public static final zw M;
    public static final zw N;
    public static final zw O;
    public static final zw P;
    public static final yj Q;
    public static final yj R;
    public static final yj S;
    public static final yj T;
    public static final yj U;
    public static final yj V;
    public static final yj W;
    public static final yj X;
    public static final yj Y;
    public static final yj Z;
    public static final yj aa;
    public static final yj ab;
    public static final yj ac;
    public static final yj ad;
    public static final yj ae;
    public static final yj af;
    public static final yj ag;
    public static final yj ah;
    public static final yj ai;
    public static final yj aj;
    public static final zw ak;
    public static final zw al;
    public static final zw am;
    public static final zw an;
    public static final zw ao;
    public static final zw ap;
    public static final zw aq;
    public static final zw ar;
    public static final zw as;
    public static final zw at;
    public static final zw au;
    public static final zw av;
    public static final zw aw;
    public static final zw ax;
    public static final zw ay;
    public static final zw az;
    public static final zw aA;
    public static final zw aB;
    public static final zw aC;
    public static final zw aD;
    public static final zw aE;
    public static final zw aF;
    public static final zw aG;
    public static final zw aH;
    public static final zw aI;
    public static final zw aJ;
    public static final zw aK;
    public static final zw aL;
    public static final zw aM;
    public static final zw aN;
    public static final zw aO;
    public static final zw aP;
    public static final zw aQ;
    public static final zq aR;
    public static final zw aS;
    public static final zw aT;
    public static final zw aU;
    public static final zw aV;
    public static final zw aW;
    public static final zw aX;
    public static final zw aY;
    public static final zw aZ;
    public static final zw ba;
    public static final zw bb;
    public static final zw bc;
    public static final aab bd;
    public static final aap be;
    public static final zw bf;
    public static final zw bg;
    public static final zw bh;
    public static final zw bi;
    public static final zw bj;
    public static final zw bk;
    public static final zw bl;
    public static final zw bm;
    public static final zw bn;
    public static final zw bo;
    public static final zw bp;
    public static final zw bq;
    public static final zw br;
    public static final zw bs;
    public static final zw bt;
    public static final zw bu;
    public static final zw bv;
    public static final zw bw;
    public static final zw bx;
    public static final zw by;
    public static final aai bz;
    public static final zw bA;
    public static final zw bB;
    public static final zw bC;
    public static final zw bD;
    public static final zw bE;
    public static final zw bF;
    public static final zw bG;
    public static final zw bH;
    public static final zw bI;
    public static final zw bJ;
    public static final zw bK;
    public static final zw bL;
    public static final zw bM;
    public static final zw bN;
    public static final zw bO;
    public static final zw bP;
    public static final zw bQ;
    public static final zw bR;
    public static final zw bS;
    public static final zw bT;
    public static final zw bU;
    public static final zh bV;
    public static final zw bW;
    public static final zw bX;
    public static final zw bY;
    public static final zw bZ;
    public static final zw ca;
    public static final zw cb;
    public static final zw cc;
    public static final zi cd;
    public static final zw ce;
    public static final zw cf;
    public static final zw cg;
    public static final zw ch;
    public static final zw ci;
    public static final yk cj;
    public static final zw ck;
    public static final zw cl;
    public static final zw cm;
    public static final zw cn;
    public static final zw co;
    public static final zw cp;
    public static final zw cq;
    public static final zw cr;
    public static final zw cs;
    public static final zw ct;
    public static final zw cu;
    public static final zw cv;
    public static final zw cw;
    public static final zw cx;
    public static final zw cy;
    public static final zw cz;
    public static final zw cA;
    public static final zw cB;
    public static final zw cC;
    public static final zw cD;
    public static final zw cE;

    private static zw a(String string) {
        return zw.e.a(new jy(string));
    }

    static {
        if (!kb.a()) {
            throw new RuntimeException("Accessed Items before Bootstrap!");
        }
        a = zy.a("iron_shovel");
        b = zy.a("iron_pickaxe");
        c = zy.a("iron_axe");
        d = zy.a("flint_and_steel");
        e = zy.a("apple");
        f = (yt)zy.a("bow");
        g = zy.a("arrow");
        h = zy.a("coal");
        i = zy.a("diamond");
        j = zy.a("iron_ingot");
        k = zy.a("gold_ingot");
        l = zy.a("iron_sword");
        m = zy.a("wooden_sword");
        n = zy.a("wooden_shovel");
        o = zy.a("wooden_pickaxe");
        p = zy.a("wooden_axe");
        q = zy.a("stone_sword");
        r = zy.a("stone_shovel");
        s = zy.a("stone_pickaxe");
        t = zy.a("stone_axe");
        u = zy.a("diamond_sword");
        v = zy.a("diamond_shovel");
        w = zy.a("diamond_pickaxe");
        x = zy.a("diamond_axe");
        y = zy.a("stick");
        z = zy.a("bowl");
        A = zy.a("mushroom_stew");
        B = zy.a("golden_sword");
        C = zy.a("golden_shovel");
        D = zy.a("golden_pickaxe");
        E = zy.a("golden_axe");
        F = zy.a("string");
        G = zy.a("feather");
        H = zy.a("gunpowder");
        I = zy.a("wooden_hoe");
        J = zy.a("stone_hoe");
        K = zy.a("iron_hoe");
        L = zy.a("diamond_hoe");
        M = zy.a("golden_hoe");
        N = zy.a("wheat_seeds");
        O = zy.a("wheat");
        P = zy.a("bread");
        Q = (yj)zy.a("leather_helmet");
        R = (yj)zy.a("leather_chestplate");
        S = (yj)zy.a("leather_leggings");
        T = (yj)zy.a("leather_boots");
        U = (yj)zy.a("chainmail_helmet");
        V = (yj)zy.a("chainmail_chestplate");
        W = (yj)zy.a("chainmail_leggings");
        X = (yj)zy.a("chainmail_boots");
        Y = (yj)zy.a("iron_helmet");
        Z = (yj)zy.a("iron_chestplate");
        aa = (yj)zy.a("iron_leggings");
        ab = (yj)zy.a("iron_boots");
        ac = (yj)zy.a("diamond_helmet");
        ad = (yj)zy.a("diamond_chestplate");
        ae = (yj)zy.a("diamond_leggings");
        af = (yj)zy.a("diamond_boots");
        ag = (yj)zy.a("golden_helmet");
        ah = (yj)zy.a("golden_chestplate");
        ai = (yj)zy.a("golden_leggings");
        aj = (yj)zy.a("golden_boots");
        ak = zy.a("flint");
        al = zy.a("porkchop");
        am = zy.a("cooked_porkchop");
        an = zy.a("painting");
        ao = zy.a("golden_apple");
        ap = zy.a("sign");
        aq = zy.a("wooden_door");
        ar = zy.a("spruce_door");
        as = zy.a("birch_door");
        at = zy.a("jungle_door");
        au = zy.a("acacia_door");
        av = zy.a("dark_oak_door");
        aw = zy.a("bucket");
        ax = zy.a("water_bucket");
        ay = zy.a("lava_bucket");
        az = zy.a("minecart");
        aA = zy.a("saddle");
        aB = zy.a("iron_door");
        aC = zy.a("redstone");
        aD = zy.a("snowball");
        aE = zy.a("boat");
        aF = zy.a("leather");
        aG = zy.a("milk_bucket");
        aH = zy.a("brick");
        aI = zy.a("clay_ball");
        aJ = zy.a("reeds");
        aK = zy.a("paper");
        aL = zy.a("book");
        aM = zy.a("slime_ball");
        aN = zy.a("chest_minecart");
        aO = zy.a("furnace_minecart");
        aP = zy.a("egg");
        aQ = zy.a("compass");
        aR = (zq)zy.a("fishing_rod");
        aS = zy.a("clock");
        aT = zy.a("glowstone_dust");
        aU = zy.a("fish");
        aV = zy.a("cooked_fish");
        aW = zy.a("dye");
        aX = zy.a("bone");
        aY = zy.a("sugar");
        aZ = zy.a("cake");
        ba = zy.a("bed");
        bb = zy.a("repeater");
        bc = zy.a("cookie");
        bd = (aab)zy.a("filled_map");
        be = (aap)zy.a("shears");
        bf = zy.a("melon");
        bg = zy.a("pumpkin_seeds");
        bh = zy.a("melon_seeds");
        bi = zy.a("beef");
        bj = zy.a("cooked_beef");
        bk = zy.a("chicken");
        bl = zy.a("cooked_chicken");
        bm = zy.a("mutton");
        bn = zy.a("cooked_mutton");
        bo = zy.a("rabbit");
        bp = zy.a("cooked_rabbit");
        bq = zy.a("rabbit_stew");
        br = zy.a("rabbit_foot");
        bs = zy.a("rabbit_hide");
        bt = zy.a("rotten_flesh");
        bu = zy.a("ender_pearl");
        bv = zy.a("blaze_rod");
        bw = zy.a("ghast_tear");
        bx = zy.a("gold_nugget");
        by = zy.a("nether_wart");
        bz = (aai)zy.a("potion");
        bA = zy.a("glass_bottle");
        bB = zy.a("spider_eye");
        bC = zy.a("fermented_spider_eye");
        bD = zy.a("blaze_powder");
        bE = zy.a("magma_cream");
        bF = zy.a("brewing_stand");
        bG = zy.a("cauldron");
        bH = zy.a("ender_eye");
        bI = zy.a("speckled_melon");
        bJ = zy.a("spawn_egg");
        bK = zy.a("experience_bottle");
        bL = zy.a("fire_charge");
        bM = zy.a("writable_book");
        bN = zy.a("written_book");
        bO = zy.a("emerald");
        bP = zy.a("item_frame");
        bQ = zy.a("flower_pot");
        bR = zy.a("carrot");
        bS = zy.a("potato");
        bT = zy.a("baked_potato");
        bU = zy.a("poisonous_potato");
        bV = (zh)zy.a("map");
        bW = zy.a("golden_carrot");
        bX = zy.a("skull");
        bY = zy.a("carrot_on_a_stick");
        bZ = zy.a("nether_star");
        ca = zy.a("pumpkin_pie");
        cb = zy.a("fireworks");
        cc = zy.a("firework_charge");
        cd = (zi)zy.a("enchanted_book");
        ce = zy.a("comparator");
        cf = zy.a("netherbrick");
        cg = zy.a("quartz");
        ch = zy.a("tnt_minecart");
        ci = zy.a("hopper_minecart");
        cj = (yk)zy.a("armor_stand");
        ck = zy.a("iron_horse_armor");
        cl = zy.a("golden_horse_armor");
        cm = zy.a("diamond_horse_armor");
        cn = zy.a("lead");
        co = zy.a("name_tag");
        cp = zy.a("command_block_minecart");
        cq = zy.a("record_13");
        cr = zy.a("record_cat");
        cs = zy.a("record_blocks");
        ct = zy.a("record_chirp");
        cu = zy.a("record_far");
        cv = zy.a("record_mall");
        cw = zy.a("record_mellohi");
        cx = zy.a("record_stal");
        cy = zy.a("record_strad");
        cz = zy.a("record_ward");
        cA = zy.a("record_11");
        cB = zy.a("record_wait");
        cC = zy.a("prismarine_shard");
        cD = zy.a("prismarine_crystals");
        cE = zy.a("banner");
    }
}

